### ISSUE TITLE
How to pass GET parameters or the whole QUERY_STRING

### ISSUE THREAD

**Issue by tpokorra** [ZonRobin/php-proxy#15]
I can see references to _GET in the code, but only in the debug area.
In the curl_init call there is no mention of the GET parameters.

In my situation, I want to proxy also GET calls. 
I have a hardcoded targetURL, so I don't have an issue reusing the QUERY_STRING as it is.

**Comment by zounar** [comment]
`$_GET` parameters are passed as-is with `HTTP_PROXY_TARGET_URL` header, thus don't require any additional manipulation.
