### ISSUE TITLE
Php version

### ISSUE THREAD

**Issue by ksverchkov** [ZonRobin/php-proxy#18]
For which php version is it made?

**Comment by ksverchkov** [comment]
And which is the minimal version?

**Comment by zounar** [comment]
Hi, the minimal version is PHP 5.6 as stated in [README.md](https://github.com/zounar/php-proxy/blob/master/README.md).

**Comment by ksverchkov** [comment]
I try to use proxy checker to check if proxy works and it is not working.
I am using PHP 8.2.0RC7 (cli) (built: Nov 22 2022 18:07:40) (NTS)

**Comment by zounar** [comment]
Please provide steps to reproduce and the actual result, thanks 🙏.

**Comment by ksverchkov** [comment]
Create a repl with template "Php web server" on repl.it and put content of Proxy.php to index.php.
Go to any proxy checker website and put the websiteurl:443 to content of list of proxies and it will tell, that it is not working or not a proxy.

**Comment by zounar** [comment]
Please, read [README.md](https://github.com/zounar/php-proxy/blob/master/README.md) beforehand. This script requires you to set `Proxy-Auth` and `Proxy-Target-URL` headers in order to work.
