### ISSUE TITLE
can it replace all the url about one site just like www.a.com/*,"*"can be abc or ...

### ISSUE THREAD

**Issue by Jeffery186** [ZonRobin/php-proxy#2]
hi,you code is very good,i just want ask can it replace all the url about one site just like www.a.com/*,"*"can be abc or ...
thank you!

**Comment by zounar** [comment]
Hi, thanks for sharing this idea. As far as I understand, you'd like to replace all links on the "target" site. 
Is this so you could navigate on the site just as some online web-proxy serivces (eg. https://proxysite.com) do? While I find this feature very useful, it would be non-trivial task involving several new functions.
