### ISSUE TITLE
Broken URL's

### ISSUE THREAD

**Issue by oleteacher** [ZonRobin/php-proxy#6]
Great script, thanks for sharing!

Using your example:

```
$request = curl_init('https://xxxxxxxx.net/prox/Proxy.php');

curl_setopt($request, CURLOPT_HTTPHEADER, array(
    'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0',
    'Proxy-Auth: Bj5pnZEX6DkcG6Nz6AjDUT1bvcGRVhRaXDuKDX9CjsAc7',
    'Proxy-Target-URL: https://www.github.com'
));

curl_exec($request);
```
Once the GitHub page loads into browser, all the URL's in their menu become something like https://xxxxxxxx.net/enterprise and that of course is a 404.

Is there any way to use the loaded site with all remote links working?

**Comment by zounar** [comment]
Hi,
thanks for raising the question. While I understand your use-case, this script is not meant to be used this way. It's primary use-case is to proxy HTTP requests that are made programmatically, not by browsing the response. I'd love to have a feature you describe above, but such task is non-trivial and might require to completely redesign the script.
I think a project like https://github.com/Athlon1600/php-proxy-app might have fit your needs better :wink:.

**Comment by oleteacher** [comment]
Totally understand you point. Thanks for taking time to explain.
