### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by PRFinklemeister** [ZonRobin/php-proxy#9]
This is a really nice module, thanks for providing it! As a complete noob I will apologize in advance. I'm curious how I can use this as a browser? I'm able to curl proxy.php like in the example, but all I get is TEXT to my shell. Even if I save the response to a variable, then what?

**Comment by zounar** [comment]
Hi,
could you provide the minimal code example or describe your use-case? This script is not meant to behave like a browser, it only programatically proxies individual HTTP requests.
It's very likely that the text in your shell is a HTML code of target website.
